#!/usr/bin/env bash
set -euo pipefail

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
testBuildPath="$NAVI_HOME/builds/test"
dockerTestPath="$NAVI_HOME/test/docker"

cd "$NAVI_HOME"

echo "Clean old test build..."
rm -rf $testBuildPath
mkdir -p $testBuildPath

echo "Building..."
# cp -r $NAVI_HOME $testBuildPath
rsync -a --progress $NAVI_HOME /$testBuildPath --exclude builds &> /dev/null

echo "Deploy to docker test path..."
rm -rf $dockerTestPath/navi
cp -r $testBuildPath/navi $dockerTestPath/navi

echo "Build test finished"
