FROM ubuntu:latest

RUN apt-get update && apt-get install -y openssh-server && apt-get install -y make && apt-get install -y git && apt-get install -y sudo
RUN mkdir /var/run/sshd
RUN echo 'root:wanghan321' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN useradd --no-log-init --create-home --shell /bin/bash wahan
RUN echo 'wahan:wanghan321' | chpasswd && adduser wahan sudo

WORKDIR /home/wahan

COPY --chown=wahan ./navi navi

USER wahan
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
RUN ~/.fzf/install

USER root
WORKDIR /home/wahan/navi
RUN make install

EXPOSE 22
#CMD ["/usr/sbin/sshd", "-D"]
